services:
  kanban-db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_kanban:/var/lib/postgresql/data
    ports:
      - 5132:5432
    restart: always
    networks:
      - kanban-networks
  
  kanban-backend:
    build: 
      context: ./backend
    container_name: kanban-backend
    env_file:
      - .env
    ports:
      - 8001:8001
    depends_on:
       - kanban-db
    restart: always
    networks:
      - kanban-networks
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start"

volumes:
  postgres_data_kanban:

networks:
  kanban-networks:
    external: true

